### ISSUE TITLE
Buttons Issue

### ISSUE THREAD

**Issue by januridp** [coronatorid/coronator#1]
![Screenshot_2021-01-01-19-34-04-407_com.codeflunce.coronator.jpg](https://user-images.githubusercontent.com/7739709/103440630-c6808f80-4c79-11eb-981a-4e6b82477dc4.jpg)

![Screenshot_2021-01-01-19-34-33-796_com.codeflunce.coronator.jpg](https://user-images.githubusercontent.com/7739709/103440658-0778a400-4c7a-11eb-9612-0a1c7d22155d.jpg)

Button doesn't look like a button

Device: Xiaomi Redmi Note 4

**Comment by insomnius** [comment]
Thank you issuenya, nanti akan di fix ya

**Comment by insomnius** [comment]
Untuk warnanya butuh saran, ada ide @januridp ?

**Comment by januridp** [comment]
> Untuk warnanya butuh saran, ada ide @januridp ?

![IMG_20210101_214759_770.jpg](https://user-images.githubusercontent.com/7739709/103440769-0c8a2300-4c7b-11eb-972e-c301957705e9.jpg)

![IMG_20210101_214802_985.jpg](https://user-images.githubusercontent.com/7739709/103440772-1449c780-4c7b-11eb-8d97-2f9313811e6b.jpg)

Mungkin bisa mengikuti pallet berikut
Semoga membantu

**Comment by insomnius** [comment]
Nice, thank you saran-nya.

**Comment by insomnius** [comment]
Fixed here: https://github.com/coronatorid/coronator/releases/tag/0.0.2

Btw nice to have banget kalau informasi schema warnanya di taruh di readme juga.

**Comment by januridp** [comment]
> Fixed here: https://github.com/coronatorid/coronator/releases/tag/0.0.2
> 
> Btw nice to have banget kalau informasi schema warnanya di taruh di readme juga.

already make a PR about it -> #3
